test: case1 case2 case3 case4 case5 case6 case7

case1:
	go run . -k 2 -n data/table.txt && echo "\n"

case2:
	cat data/table.txt | go run . -k 2 -nr && echo "\n"

case3:
	go run . -k 3 -M data/table.txt && echo "\n"

case4:
	go run . -k 3 -Mr data/table.txt && echo "\n"

case5:
	go run . -k 4 -h data/table.txt && echo "\n"

case6:
	go run . -k 1 -cn data/table.txt && echo "\n"

case7:
	go run . -k 2 -c data/table.txt; echo "\n"